vectorizer_param_grid:
  max_features: [80000, 50000, 30000]
  ngram_range:
    - !!python/tuple [1, 2]
    - !!python/tuple [1, 3]
    - !!python/tuple [2, 3]
  stop_words: [english]
  lowercase: [true]
  use_idf: [true, false]
  smooth_idf: [true, false]
  sublinear_tf: [true, false]

grid_search_params:
  C: [0.5, 1, 2]
  tol: [1.0e-5, 1.0e-4, 1.0e-3]
  max_iter: [1000, 2000, 3000, 4000]
  class_weight: [null, balanced]